### ISSUE TITLE
Add support for IPv4 and IPv6 datatypes 

### ISSUE THREAD

**Issue by maciej** [mailru/go-clickhouse#100]
* https://clickhouse.tech/docs/en/sql-reference/data-types/domains/ipv4/
* https://clickhouse.tech/docs/en/sql-reference/data-types/domains/ipv6/

which are currently unsupported:
https://github.com/mailru/go-clickhouse/blob/master/dataparser.go#L399-L494

**Comment by forward32** [comment]
I got into same situation and used `IPv4NumToString()`/`IPv6NumToString()` ClickHouse functions as workaround.
It's not very convenient but works.
