### ISSUE TITLE
dsn parse errror

### ISSUE THREAD

**Issue by UZER0** [mailru/go-clickhouse#104]
dsn: http://default:aaaaa/bbbb/cccc@127.0.0.1:10001/
Connect(function): parse http://default:aaaaa/bbbb/cccc@127.0.0.1:10001/: invalid port \":aaaaa\" after host

**Comment by Slach** [comment]
did you try to pass connection PASSWORD with backslash character `/`?
quick workaround
`http://127.0.0.1:10001/?user=default&password=password/with/backslash`

**Comment by UZER0** [comment]
@Slach I create new password not contain backslash character / .Now It's worked.thank you。
