### ISSUE TITLE
How to INSERT UUID field in columnar mode

### ISSUE THREAD

**Issue by mosajjal** [mailru/go-clickhouse#105]
Hi,

I'm having some issues batch INSERTing rows with the columnar dialect. even in the `clickhouse_columnar_test.go` unit test, there's no UUID insert as an example. Can you please provide some documentation on how this should be done. 

Thanks

**Comment by DoubleDi** [comment]
Wrong repo, please add a question to https://github.com/clickhouse/clickhouse-go
