### ISSUE TITLE
Driver doesn't return an error on creating table on cluster with wrong data type

### ISSUE THREAD

**Issue by xtreding** [mailru/go-clickhouse#106]
Step to reproduce:
```
connect, err := sql.Open("clickhouse", "http://127.0.0.1:8123/default")
	if err != nil {
		log.Fatal(err)
	}
	if err := connect.Ping(); err != nil {
		log.Fatal(err)
	}

	_, err = connect.Exec(`
		CREATE TABLE "default"."test_driver_1"  
                 ON CLUSTER "mycluster"  
                     (_timestamp DateTime, wrongcolumn Lowcardinality(String)) 
                 ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/default/test_driver_1', '{replica}', _timestamp) 
                 PARTITION BY (toYYYYMM(_timestamp)) 
                 ORDER BY (_timestamp)
	`)

	if err != nil {
		log.Fatal(err)
	}
```

Actual behavior: no error (but the table isn't created)

Expected behavior: error `Code: 50, e.displayText() = DB::Exception: There was an error on [clickhouse2:9000]: Code: 50, e.displayText() = DB::Exception: Unknown data type family: Lowcardinality. Maybe you meant: ['LowCardinality'] (version 20.9.3.45 (official build)) (version 20.9.3.45 (official build)`

**Comment by xtreding** [comment]
ClickHouse/ClickHouse#18002 fixed

**Comment by aksdb** [comment]
Is this a fix, though? It seems it just shadows the problem since Clickhouse seems to prefer streaming the answer (which makes sense I guess, especially with queries returning actual query results.)
