### ISSUE TITLE
uint64 values with high bit set are not supported

### ISSUE THREAD

**Issue by ignishub** [mailru/go-clickhouse#11]
В ридми вы пишите что поддерживаете uint64 Но при записи в базу мне возвращается эта ошибка. Не подскажите пожалуйстак ак это можно решить?

**Comment by bgaifullin** [comment]
проблема в пакете database/sql https://github.com/golang/go/issues/9373
можно попробовать заимплеменить интерфейс database.driver.Valuer для такого большого uint64 и при передаче в запрос оборачивать ваше число.

**Comment by ignishub** [comment]
Спасибо большое за ответ! Попробую этот вариант.

Но тогда возможно следует указать в ридми что uint64 не поддерживается полностью? Ведь это ставит в небольшой тупик так как кликхаус поддерживает этот тип и я думаю в базе статистики это важный момент

Еще раз спасибо!

**Comment by bgaifullin** [comment]
Спасибо большое за замечание. Я обязательно исправлю это. :)

**Comment by bgaifullin** [comment]
добавил тип UInt64, в который можно оборачивать большие числа uint64.

**Comment by ignishub** [comment]
Спасибо!
