### ISSUE TITLE
gzip (or any other compression) for inserts

### ISSUE THREAD

**Issue by SlavaVV** [mailru/go-clickhouse#112]
gzip works on selects only. What about Inserts?

**Comment by DoubleDi** [comment]
We are using enable_http_compression opt for compressing requests.
https://clickhouse.tech/docs/en/operations/settings/settings/#settings-enable_http_compression
The doc states, that it gzips the response body only. I don't clickhouse can do that yet. But maybe i am wrong.
What option are you talking about?

**Comment by SlavaVV** [comment]
Exactly - enable_http_compression. This library (go-clickhouse) uses golang http connection which has builtin gzip for reading. So I can enable http compression, run selects and I will get gzipped data. gzip will be under-hood in golang http connection.
BUT if I will send data golang http will not gzip body. So if I send bunch of inserts - they will be sent as is.
I modified buildRequest method in conn.go  - added gzip data. Now it sends gzipped body
If somebody need - I can send the code, it's simple.

**Comment by DoubleDi** [comment]
Found some information that if you enable http compression and add `Content-Encoding: compression_method` you can easily send compressed data. Great idea. PR is welcome

**Comment by SlavaVV** [comment]
Not a specialist in this. I attach file - feel free to it
[conn.zip](https://github.com/mailru/go-clickhouse/files/6001582/conn.zip)
