### ISSUE TITLE
Invalid datetime encoding

### ISSUE THREAD

**Issue by komly** [mailru/go-clickhouse#12]
If I insert datetime with zeroes in second, minute and hour like "2017-12-29 00:00:00" I got error
"error":"clickhouse: Code: 41, e.displayText() = DB::Exception: Cannot parse datetime 2017-12-29: (at row 1)\n, e.what() = DB::Exception\n"

formatTime() function works incorrect way

**Comment by bgaifullin** [comment]
Thank you for bug report. 
the issue is resolved.
