### ISSUE TITLE
golint is deprecated

### ISSUE THREAD

**Issue by finnan444** [mailru/go-clickhouse#123]
Perhaps you can use [revive](https://github.com/mgechev/revive) insted of archived golint.
Or even better more complex solution - https://golangci-lint.run

**Comment by DoubleDi** [comment]
yes will be considering this, thanks

**Comment by DoubleDi** [comment]
PR's for golangci are welcome

**Comment by finnan444** [comment]
@DoubleDi [enhanced](https://github.com/mailru/go-clickhouse/pull/129) a liitle bit golang-ci rules
