### ISSUE TITLE
How to use where in with multiple fields?

### ISSUE THREAD

**Issue by maxifom** [mailru/go-clickhouse#125]
I want to use something like this:
`SELECT * FROM a WHERE (a,b) IN ((1,2),(2,3)`. How to do this with sql/sqlx with clickhouse driver?

**Comment by finnan444** [comment]
I guess `clickhouse.Tuple` type is not implemented

**Comment by DoubleDi** [comment]
Tuple is being parsed, but you can't actually pass it yes. 
We are parsing a tuple to a struct so we can pass a wrapper for a struct that it will transform to a Tuple. 
```
clickhouse.Tuple(struct { A string, B int }{"1",2}) -> ("1",2)
```
PR is welcome. Will try to implement this in the future
