### ISSUE TITLE
The behavior of binding an array var

### ISSUE THREAD

**Issue by jadetang** [mailru/go-clickhouse#134]
hi, I found that when the var is an array, the driver will interpolate the value as a string without brackets. 
example:

```golang
stmt, err := tx.Prepare("select * from persons where  hasAny(array, ? )")
_, err = stmt.Exec([]string{"k1", "v1"})
```
The generated SQL is syntax wrong.
```sql
select * from persons where hasAny(array, 'k1', 'v1')
```
As a workaround, I change my SQL to this 
```sql
select * from persons where  hasAny(array, [?] )
```
and the generated SQL is accepted by the server
```sql
select * from persons where hasAny(array, ['k1', 'v1'])
```

However, this looks like a small bug to me. Will this behavior change in the future version?

**Comment by DoubleDi** [comment]
Hi @jadetang !
That's the default behavior for using arrays in IN query. If you want to have brackets, use 
`clickhouse.Array()` wrapper
