### ISSUE TITLE
Add new version tag

### ISSUE THREAD

**Issue by z0rr0** [mailru/go-clickhouse#140]
Hi,

Could you please increment the [release version](https://github.com/mailru/go-clickhouse/releases/)?
The current value is [1.6.0](https://github.com/mailru/go-clickhouse/releases/tag/v1.6.0) (2021-05-28 6d7c56f), but there are some interesting fixes/improvements after that. So it would be good to have a new minor/major version.

**Comment by DoubleDi** [comment]
Hi!

Presenting  v1.7.0
