### ISSUE TITLE
How to limit the query time

### ISSUE THREAD

**Issue by byzhaozihan** [mailru/go-clickhouse#147]
When I execute an aggregate query statement with a very large amount of data, I try to set read_timeout=10s. I hope that the query time exceeds 10 seconds and the timeout exception will be returned, but why doesn’t it work? What can I do to limit the query time?

**Comment by ElrondfromRussia** [comment]
@byzhaozihan  Hi! I used sqlx.QueryWithContext() function (with timeout context) when faced this problem some month ago.

**Comment by byzhaozihan** [comment]
@ElrondfromRussia It works, thanks a lot!

**Comment by ElrondfromRussia** [comment]
@byzhaozihan you're welcome)
