### ISSUE TITLE
Functions in SELECT Query builder column names

### ISSUE THREAD

**Issue by sir-farfan** [mailru/go-clickhouse#152]
Hello there
I just found about this library and I'm thinking about moving from clickhouse-go and sqlx.

I had issues with other query builders when trying to use functions as column names like this:
```sql
SELECT formatDateTime(time, '%Y-%m-%d', 'US/General') AS day FROM table
```
I'm wondering if that's somehow supported by your solution.

**Comment by DoubleDi** [comment]
your query will be returning a string, so you can scan the value in to a string and parse it into a time.Time if you like. Or make a wrapper type Date.

Or you can use toDate(time) and return a Date type and the driver will parse it into a time.Time for you

**Comment by sir-farfan** [comment]
Thanks :)
