### ISSUE TITLE
Manuel registration doesn't work

### ISSUE THREAD

**Issue by cemezgin** [mailru/go-clickhouse#176]
I want to use clickhouse with the datadog tracing.
https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql

But because of driver is not exported, i am not able to register and use driver.

```
func init() {
	sql.Register("chhttp", new(chDriver))
}

// chDriver implements sql.Driver interface
type chDriver struct {
}

// Open returns new db connection
func (d *chDriver) Open(dsn string) (driver.Conn, error) {
	cfg, err := ParseDSN(dsn)
	if err != nil {
		return nil, err
	}
	return newConn(cfg), nil
}
```

Is there any reason why it is not exported?

**Comment by DoubleDi** [comment]
Thanks for the usecase. PR welcome to export the driver
