### ISSUE TITLE
Can't differentiate between DateTime64 and Date32 type

### ISSUE THREAD

**Issue by KarelRoy** [mailru/go-clickhouse#184]
Since the Date type is now implemented using time.Time, is it impossible to distinguish between Date32 and DateTime64 types?

**Comment by DoubleDi** [comment]
Hello, can you provide an example of the issue?

**Comment by KarelRoy** [comment]
Thanks for your reply, I seem to have found the answer.
Use DatabaseTypeName Func to know whether it is Date or DateTime type
