### ISSUE TITLE
Kill query не будет выполнен, если были аргументы в запросе

### ISSUE THREAD

**Issue by kirphone** [mailru/go-clickhouse#185]
Привет, у вас тут походу баг с килом запросов при таймауте. В conn.go вот такое:
body, err := c.doRequest(ctx, req)
    if err != nil {
        if _, ok := err.(*Error); !ok && err != driver.ErrBadConn {
            killErr := c.killQuery(req, args)
            if killErr != nil {
                c.log("error from killQuery", killErr)
            }
        }
        return nil, err
    }

То есть вы пытаетесь в запрос на килл запроса подставить параметры из нашего запроса (внутри killQuery это есть). Если у нас были какие-то параметры в запросе, то у вас ничего не получится и получим ошибку. Причем эта ошибка никуда не вернется (killErr). Можем это поправить?

**Comment by Slach** [comment]
@kirphone сделайте Pull Request его скорее всего примут
