### ISSUE TITLE
Code: 73, Message: Unknown format TSVWithNamesAndTypes

### ISSUE THREAD

**Issue by romanitalian** [mailru/go-clickhouse#3]
I just copy past code: https://github.com/mailru/go-clickhouse#example
And run it in console.

```go
2017/08/07 21:53:05 Code: 73, Message: Unknown format TSVWithNamesAndTypes
exit status 1
```
https://gist.github.com/romanitalian/6ad1d22ba1db816748a441bdfa133758

uname -a
`2.6.32-042stab105.14 #1 SMP Fri Mar 13 20:06:37 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bgaifullin** [comment]
Hi. Could you please add version of clickhouse-server to the issue.

**Comment by romanitalian** [comment]
ClickHouse version: 1.1.54030

**Comment by bgaifullin** [comment]
Could you please confirm that branch fix-issue-3 forks for your case.

**Comment by romanitalian** [comment]
Yes I do, I could confirm that branch **fix-issue-3 forks** for my case.
How can I get code from branch [fix-issue-3] with patch and test it - `go get ... ` ?

**Comment by bgaifullin** [comment]
you can get package via go get and after that switch to required branch.

```
cd $GOPATH/src/github.com/mailru/go-clickhouse
git checkout fix-issue-3
```

**Comment by bgaifullin** [comment]
I have merged fix.
thank you for help.

**Comment by romanitalian** [comment]
Thank you! It works correct now :)
