### ISSUE TITLE
[]uint8{} encoded as empty string

### ISSUE THREAD

**Issue by francisdb** [mailru/go-clickhouse#35]
what's the reason for doing this?
https://github.com/mailru/go-clickhouse/blob/8fe4eab1f729d3b76089567789b55de476042a4b/encoder.go#L74-L75

We have a column `diff UInt8`  in a `Nested` column which requires to insert field.diff as  `Array(UInt8)` but the driver seems to encode `[]uInt8` as a string which in case of an empty array gives you the empty string.

```
insert: Code: 62, Message: Cannot parse expression of type Array(UInt8) here: , 0)
```

_Also this could be dangerous regarding sql injections._

**Comment by francisdb** [comment]
we are using `clickhouse.Array([]uint8{})` but that does not help, using a go native array however does (wrapped or not)

**Comment by bgaifullin** [comment]
Thanks for your contribution, I found a real bug in code and prepare fix.

**Comment by francisdb** [comment]
I can confirm this to be fixed
