### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by im-kulikov** [mailru/go-clickhouse#48]
Same issue https://github.com/mailru/dbr/issues/16

In order not to break anything, I suggest to add the following tags:
- v1.1.0 -> [v1.1](
https://github.com/mailru/go-clickhouse/releases/tag/v1.1)
- v1.0.0 -> [v1.0](
https://github.com/mailru/go-clickhouse/releases/tag/v1.0)

**For now, after `go mod tidy` I have:**
```
module some/project

require (
	...
	github.com/mailru/go-clickhouse v0.0.0-20180822112201-2af3abdc4318 // indirect
	...
)

**Comment by bgaifullin** [comment]
added tags 1.1.0 and 1.0.0.
Thank you for report.

**Comment by im-kulikov** [comment]
Thx!
