### ISSUE TITLE
Closing conn on stmt close

### ISSUE THREAD

**Issue by theoptz** [mailru/go-clickhouse#49]
```
// Close closes the statement.
func (s *stmt) Close() error {
	if atomic.CompareAndSwapInt32(&s.closed, 0, 1) {
		s.c = nil
	}
	return nil
}
```

As you can see in this code `s.c` hasn't been closed.
In my application i've got memory leak here. I've tried to use timeout and idle_timeout settings but it didn't help.

For me i've fixed this issue like this:
```
// Close closes the statement.
func (s *stmt) Close() error {
	if atomic.CompareAndSwapInt32(&s.closed, 0, 1) {
		if s.c != nil {
			s.c.Close()
		}
		s.c = nil
	}
	return nil
}
```

Is this a bug or i'm doing something wrong?

**Comment by bgaifullin** [comment]
The connection should not be closed here, since you can create several statements by using single connection. you need to close connection object, when it is not more needed.
