### ISSUE TITLE
Potential memory leak on conn exec

### ISSUE THREAD

**Issue by theoptz** [mailru/go-clickhouse#50]
Take a look on this part of code

```
func (c *conn) exec(ctx context.Context, query string, args []driver.Value) (driver.Result, error) {
	// ...
	_, err = c.doRequest(ctx, req)
	return emptyResult, err
}
```

`doRequest` returns response body and in this case body hasn't been closed. I guess this is possible memory leak because the connection could remain open. I've got this issue in my application.

This could be fixed:
```
func (c *conn) exec(ctx context.Context, query string, args []driver.Value) (driver.Result, error) {
	// ...
	body, err = c.doRequest(ctx, req)
        if body != nil {
           body.Close()
        }
	return emptyResult, err
}
```

**Comment by skyjaack** [comment]
Can confirm. It leaks when i try to often insert a batch of items
