### ISSUE TITLE
Parse error on strings with double quotes

### ISSUE THREAD

**Issue by azaikin** [mailru/go-clickhouse#51]
The following error occurs when trying to select a string field containing double quotes:
> parse error on line 1, column 2: bare " in non-quoted-field

Code to reproduce:
```golang
package main

import (
	"database/sql"
	"log"

	_ "github.com/mailru/go-clickhouse"
)

func main() {
	connect, err := sql.Open("clickhouse", "http://default@127.0.0.1:8123/default")
	if err != nil {
		log.Fatal(err)
	}

	var f1, f2 string
	err = connect.QueryRow(`SELECT '"foo" foo', 'bar'`).Scan(&f1, &f2)
	if err != nil {
		log.Fatal(err)
	}
}
```

go-clickhouse version: f16ee58559afccd90c459f6d5d09533b83e78db1
clickhouse version: 18.10.3

**Comment by bgaifullin** [comment]
Should be fixed in 47

**Comment by reqq** [comment]
Not fixed in case of a quote at the beginning of a line. If the quote is not the first character then it works fine.
