### ISSUE TITLE
wrong dsn behavior

### ISSUE THREAD

**Issue by forward32** [mailru/go-clickhouse#73]
Having this DSN
```go
        addr := fmt.Sprintf(`http://%s:8123/users?timeout=1s&debug=true`,
                r.Container.NetworkSettings.IPAddress)
```
and CH running inside container I'm trying to connect to my database (`users` in example above) with this code:
```go
        conn, err := sql.Open("clickhouse", addr)
        if err != nil {
                return nil, err
        }
        if err = conn.Ping(); err != nil {
                return nil, err
        }
```
And it always connects even database `users` doesn't exists. I expect to receive error on `sql.Open()`. Otherwise you receive error right after first query.

Should I manually check that database exists?

**Comment by forward32** [comment]
Any updates on this?

**Comment by Slach** [comment]
@forward32 this behavior is not related to driver itself, it's a specific behavior for ClickHouse server and related to HTTP protocol handler inside ClickHouse server

let me explain details
1) driver doesn't connect when you call sql.Open, most of golang drivers use lazy connection mode
2) also, when you just make tcp connection via 8123 port ClickHouse also doesn't check database is exists
3) when you call `conn.Ping` driver doesn't make http request to `/users` URL, it makes http request to `/ping` URL as described here https://clickhouse.tech/docs/en/interfaces/http/
4) so, only when you will try to make some queries like `SELECT ... FROM table_without_database_name`, driver will make HTTP request to `/users` and ClickHouse will check database and will return 404 error, which should pass back to your application

**Comment by forward32** [comment]
Ok, got it, thanks!
