### ISSUE TITLE
Time is returned with wrong Time Zone.

### ISSUE THREAD

**Issue by wb-waldemar** [mailru/go-clickhouse#82]
The latest Library received with the 'dep ensure -update' Command, has a Bug.

It returns Time with wrong Time Zone. 
The old Version of this Library returned a correct Time Zone.

I receive Time from Database into a String.
For Example, for 'MSK' Time Zone, the old Library returned Time as '2019-09-01T00:00:00+03:00' String.
The latest Library for 'MSK' Time Zone returns Time as '2019-09-01T00:00:00Z' String.

Gopkg.toml:
```
[[constraint]]
  name = "github.com/mailru/go-clickhouse"
  version = "1.1.0"
```

**Comment by DoubleDi** [comment]
Hello! Thanks for your report. 

We have already fixed this issue in this commit:
https://github.com/mailru/go-clickhouse/commit/0fd5640f1722e772c36b77565d1e75b8ee1907ee

So you shouldn't have any problems, if you update to a hash version of the commit. 
Or you can just bump up the release to v1.2.0

**Comment by DoubleDi** [comment]
@wb-waldemar  please give a status update. Can i close this issue?
