### ISSUE TITLE
Unable to connect to intermediate services expecting DSN

### ISSUE THREAD

**Issue by joe-bowman** [mailru/go-clickhouse#85]
Due to `config.url` being passed the param `dsn=false` when creating a new connection, when connecting to a service that expects the DSN to be passed in full (e.g. github.com/nikepan/clickhouse-bulk) we end up only ever being able to connect to the `default` database.

The following code from `config.url` shows that the database is set by a query, rather than as part of the dsn. 
```
	if len(cfg.Database) > 0 {
		if dsn {
			u.Path += cfg.Database
		} else {
			query.Set("database", cfg.Database)
		}
	}
```

Are we able to make this dsn flag a parameter of the call to Open?

**Comment by DoubleDi** [comment]
Hello!
We don't want to break the database/sql Driver compability. 

Can you explain please with examples what dsn you want and what you are getting

**Comment by joe-bowman** [comment]
So I'm using github.com/nikepan/clickhouse-bulk to group many of small inserts into fewer larger inserts. This works fine, but expects to be passed a DSN (much like we pass into go-clickhouse driver). Go Clickhouse however removes the /databasename path from the DSN (path is explicitly set to `/`, and instead calls a SET query on the connection once established). This is because when the connection is created, the `dsn` flag is passed into `config.url` as `false` (see code snippet above). Setting this to `true` fixes my issue, but I'm trying to determine if there is a neat way of doing this that doesn't break the driver compatibility.

**Comment by joe-bowman** [comment]
This could presumably be added as an additional DSN param `forward_dsn` which can be parsed in `ParseDSNParams()` and then https://github.com/mailru/go-clickhouse/blob/02cccac7b534137d8a596a97a788cf2e2084870f/conn.go#L51 can check the value of `cfg.ForwardDSN` instead of passing `false` (but still default to `false` for b/c).

**Comment by DoubleDi** [comment]
Sure. The ForwardDSN is a good way to fix your problem. PR is welcome

**Comment by DoubleDi** [comment]
@joe-bowman this should be fixed in current releases
