### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by AcoNCodes** [mailru/go-clickhouse#88]
Hello, after the last commit I get this error:
github.com/mailru/go-clickhouse/conn.go:308:23: multiple-value uuid.NewV4() in single-value context

**Comment by DoubleDi** [comment]
hello! Thanks for the issue. Will fix it in #87

**Comment by DoubleDi** [comment]
it was a dependency version error. The issue is now fixed. please use 1.1.0 version in uuid package

**Comment by lexand** [comment]
Is there a way to fix this (use 1.1.0 version in uuid package) but not use modules ?

**Comment by DoubleDi** [comment]
you can use dep to get the correct versions of dependencies.
Here is the [Gopkg](https://github.com/mailru/go-clickhouse/blob/master/Gopkg.toml) file
