### ISSUE TITLE
Cannot import go-clickhouse

### ISSUE THREAD

**Issue by lchoua** [mailru/go-clickhouse#94]
Hello, I am trying to use your library but when I run go get -u github.com/mailru/go-clickhouse, I get the following error:
../../../../go/src/github.com/mailru/go-clickhouse/conn.go:316:23: multiple-value uuid.NewV4() in single-value context.
 I read an other issue with the same error, but there wasn't an answer.
Thank you in advance

**Comment by vano144** [comment]
Hello, command `go get -u ...` ignores dependencies, but go-clickhouse requires github.com/satori/go.uuid v1.1.0

I suggest you try to use next command:

`GO111MODULE=on go get -u github.com/mailru/go-clickhouse`

**Comment by DoubleDi** [comment]
@vano144  how about updating #91 and fixing that issue? 
Can update the dependency in the next few days.

**Comment by vano144** [comment]
yeah, it is a good idea

**Comment by DoubleDi** [comment]
fixed this in #96
